name: Publish
on:
  push:
    tags:
      - "*" # Keeps the original trigger
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
