name: Publish
on:
  push:
    tags:
      - "*" # Keeps the original trigger
  workflow_dispatch: # Allows manual dispatch with parameters
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
